global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["amqp:15692"]

  - job_name: "docker"
    static_configs:
      - targets: ['cadvisor:8080']
